repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      # Git style
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules
      #- id: no-commit-to-branch
      # Common errors
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: CHANGELOG.md
      - id: check-yaml
        exclude: aws-cf/.*\.(yml|yaml)$|.*\.(yml|yaml)
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-ast

      # Cross platform
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

      # Security
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key

  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.72.10
    hooks:
    -   id: cfn-python-lint
        files: aws-cf/.*\.(yml|yaml)$|sam/.*\.(yml|yaml)

  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: 'v8.38.0'  # Use the sha / tag you want to point at
  #   hooks:
  #   -   id: eslint
  #       args: ["-c", "./.eslintrc.yml"]
  #       additional_dependencies:
  #       -   eslint@8.38
  #       -   eslint-plugin@latest
